version: '2'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: ../.env
    environment:
      # - POSTGRES_USER=ea_user
      # - POSTGRES_PASSWORD=ea_pwd
      # - POSTGRES_DB=ea_event_streams
      - PGDATA=/var/lib/postgresql/data/db-files
    volumes:
      - ./logs/postgresql/:/var/log/postgresql
      - ./postgres/data:/var/lib/postgresql/data/db-files
      # - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../config/scripts/postgres:/docker-entrypoint-initdb.d
      - ./postgres/.pgpass:/root/.pgpass

  php:
    build: php-fpm
    expose:
      - "9000"
    volumes:
      - ../:/var/www/symfony
      - ./logs/symfony/:/var/www/symfony/var/logs
    depends_on:
      - postgres

  nginx:
    build: nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
